server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Redirige todas las rutas de React al index.html generado por Vite
        try_files $uri $uri/ /index.html; 
    }

    # Evita que el Service Worker de la PWA se quede en la memoria caché vieja
    location = /sw.js {
        root /usr/share/nginx/html;
        add_header Cache-Control "no-cache";
    }
}