version: '3.8'
services:
  postgres-db:
    image: postgres:17
    container_name: sistema_tickets_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: sistema_tickets_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Backend
  backend:
    build: 
      context: ./backend
    container_name: sistema_tickets_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    restart: always

  # 3. Frontend en React + Nginx
  frontend:
    build:
      context: ./frontend
    container_name: sistema_tickets_frontend
    ports:
      - "80:80" 
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: