-- =========================================================================
-- V10 — Persistencia del dictamen tecnico e historial unificado
-- =========================================================================
-- Dos cambios que van juntos porque el segundo depende del primero.
--
-- 1. LOS DICTAMENES NO SE GUARDABAN EN NINGUNA PARTE
--
-- `DocumentoResource.generarDictamen()` recibia el formulario, componia el PDF
-- y lo devolvia. No habia tabla, ni entidad, ni repositorio: cada dictamen
-- emitido existia unicamente como el archivo que el tecnico descargaba en ese
-- momento. Pedir un historial de dictamenes era, hasta ahora, pedir un listado
-- de algo que el sistema nunca escribio.
--
-- Esta tabla lo corrige de aqui en adelante. Los dictamenes emitidos ANTES de
-- aplicar la migracion no son recuperables: no existe origen del que leerlos.
-- El historial arranca vacio y se llena con cada documento nuevo.
--
-- El apartado de analisis tecnico nace ya con su forma definitiva —falla
-- reportada y diagnostico— sin los campos de hallazgos y conclusion, que se
-- retiraron del formato oficial en este mismo cambio.
--
-- 2. HISTORIAL UNIFICADO EN UNA SOLA ENTRADA DE MENU
--
-- Habia dos entradas separadas ('Bitacora' e 'Historial de resguardos') y
-- ninguna para dictamenes. Se sustituyen por una sola, 'Historial', con las
-- tres consultas en pestanas.
--
-- Las rutas anteriores (/admin/bitacora y /admin/resguardos) siguen declaradas
-- en App.jsx a proposito: un enlace guardado en favoritos debe seguir abriendo
-- algo. Lo que se retira aqui es su entrada de menu, no su acceso.
--
-- Idempotente: sobre una base que ya tenga los cambios, no altera nada.
-- =========================================================================

-- --------------------------------------------------- 1. TABLA DE DICTAMENES
-- Los anchos siguen los de `equipo_reparacion`, que documenta el mismo equipo
-- fisico: 1000 para los textos largos y 100 para marca, modelo y serie.

CREATE TABLE IF NOT EXISTS public.dictamen (
    pn_id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_folio                varchar(50) NOT NULL UNIQUE,
    fn_ticket_id           bigint REFERENCES public.ticket (pn_id),

    -- Equipo dictaminado
    s_cve                  varchar(20),
    s_descripcion_equipo   varchar(255),
    s_marca                varchar(100),
    s_modelo               varchar(100),
    s_serie                varchar(100),
    s_no_resguardo         varchar(100),

    -- Servidor publico al que pertenece el equipo
    s_nombre_usuario       varchar(200),
    s_telefono_usuario     varchar(50),
    s_direccion_usuario    varchar(200),
    s_departamento_usuario varchar(150),
    s_tipo_reporte         varchar(150),

    -- Analisis tecnico: solo falla y diagnostico.
    s_falla_reportada      varchar(1000),
    s_diagnostico          varchar(1000),

    -- Firmas tal y como se imprimieron. Se guardan como texto, no como
    -- referencia al usuario: el documento debe conservar el nombre que
    -- llevaba impreso aunque la persona cambie de puesto o cause baja.
    s_realizado_por        varchar(200),
    s_revisado_por         varchar(200),
    s_recibido_por         varchar(200),

    fn_tecnico_id          bigint REFERENCES public.usuario (pn_id),

    s_creado_por           varchar(100),
    d_fecha_creacion       timestamp(6) NOT NULL,
    s_modificado_por       varchar(100),
    d_fecha_modificacion   timestamp(6)
);

-- El historial se consulta casi siempre por fecha descendente, y se busca por
-- serie o por nombre del servidor publico.
CREATE INDEX IF NOT EXISTS idx_dictamen_fecha_creacion
    ON public.dictamen (d_fecha_creacion DESC);

CREATE INDEX IF NOT EXISTS idx_dictamen_serie
    ON public.dictamen (s_serie);

CREATE INDEX IF NOT EXISTS idx_dictamen_ticket
    ON public.dictamen (fn_ticket_id);

-- ------------------------------------------------- 2. ENTRADA DE MENU NUEVA

INSERT INTO public.vista (s_nombre, s_ruta, s_icono, b_activo) VALUES
    ('Historial', '/historial', 'HistoryIcon', true)
ON CONFLICT (s_ruta) DO NOTHING;

-- Se concede a ADMINISTRADOR y a SOPORTE: el area tecnica necesita consultar
-- sus propios dictamenes y resguardos, no solo emitirlos.
INSERT INTO public.rol_vista (fn_rol_id, fn_vista_id)
SELECT r.pn_id, v.pn_id
FROM public.rol r, public.vista v
WHERE r.s_nombre IN ('ADMINISTRADOR', 'SOPORTE')
  AND v.s_ruta = '/historial'
  AND NOT EXISTS (
      SELECT 1 FROM public.rol_vista rv
      WHERE rv.fn_rol_id = r.pn_id AND rv.fn_vista_id = v.pn_id
  );

-- ------------------------------------- 3. RETIRADA DE LAS ENTRADAS ANTIGUAS
-- Solo se quita su presencia en el menu. Las rutas siguen existiendo en el
-- frontend y las pantallas se alcanzan ahora desde las pestanas del historial.

DELETE FROM public.rol_vista
WHERE fn_vista_id IN (
    SELECT pn_id FROM public.vista WHERE s_ruta IN ('/admin/bitacora', '/admin/resguardos')
);

DELETE FROM public.vista WHERE s_ruta IN ('/admin/bitacora', '/admin/resguardos');
