-- =========================================================================
-- V1 — Baseline del esquema
-- =========================================================================
-- Refleja la estructura que la base de datos YA tiene en produccion, tomada
-- del volcado real (pg_dump del 31/07/2026). No crea nada nuevo: es el punto
-- de partida a partir del cual Flyway lleva la cuenta.
--
-- Sobre una base existente, con spring.flyway.baseline-on-migrate=true y
-- baseline-version=1, Flyway marca esta migracion como aplicada SIN
-- ejecutarla, y solo corre de la V2 en adelante. Los IF NOT EXISTS permiten
-- ademas levantar el proyecto desde cero en una base vacia.
--
-- Convencion de nombres heredada del proyecto:
--   pn_  clave primaria      fn_  clave foranea
--   s_   texto               b_   booleano        d_   fecha/hora
-- =========================================================================

-- ---------------------------------------------------------------- CATALOGOS

CREATE TABLE IF NOT EXISTS public.rol (
    pn_id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_nombre         varchar(255) NOT NULL UNIQUE,
    -- GLOBAL | AREA | PERSONAL. Determina que tickets ve cada rol.
    s_nivel_vision   varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.vista (
    pn_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_nombre   varchar(100) NOT NULL,
    s_ruta     varchar(100) NOT NULL UNIQUE,
    s_icono    varchar(50),
    b_activo   boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS public.rol_vista (
    fn_rol_id    bigint NOT NULL REFERENCES public.rol (pn_id),
    fn_vista_id  bigint NOT NULL REFERENCES public.vista (pn_id)
);

CREATE TABLE IF NOT EXISTS public.estadoticket (
    pn_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_nombre  varchar(50) NOT NULL UNIQUE
);

-- ------------------------------------------------------- AREAS Y USUARIOS

CREATE TABLE IF NOT EXISTS public.area (
    pn_id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_nombre              varchar(100) NOT NULL,
    b_activo              boolean NOT NULL,
    b_prioritaria         boolean DEFAULT false,
    fn_soporte_fijo_id    bigint UNIQUE,
    s_creado_por          varchar(100),
    d_fecha_creacion      timestamp(6) NOT NULL,
    s_modificado_por      varchar(100),
    d_fecha_modificacion  timestamp(6)
);

CREATE TABLE IF NOT EXISTS public.usuario (
    pn_id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_nombre              varchar(150) NOT NULL,
    s_apellido_paterno    varchar(255),
    s_apellido_materno    varchar(255),
    s_correo              varchar(100) NOT NULL UNIQUE,
    s_username            varchar(50) UNIQUE,
    -- Hash BCrypt, nunca la contrasena en claro.
    s_password            varchar(255) NOT NULL,
    b_activo              boolean NOT NULL,
    b_disponible_soporte  boolean NOT NULL,
    b_password_temporal   boolean NOT NULL,
    telegram_chat_id      bigint,
    fn_rol_id             bigint REFERENCES public.rol (pn_id),
    fn_area_id            bigint REFERENCES public.area (pn_id),
    s_creado_por          varchar(100),
    d_fecha_creacion      timestamp(6) NOT NULL,
    s_modificado_por      varchar(100),
    d_fecha_modificacion  timestamp(6)
);

-- La clave foranea de area se anade despues, porque ambas tablas se
-- referencian mutuamente.
ALTER TABLE public.area
    DROP CONSTRAINT IF EXISTS fk_area_soporte_fijo;
ALTER TABLE public.area
    ADD CONSTRAINT fk_area_soporte_fijo
    FOREIGN KEY (fn_soporte_fijo_id) REFERENCES public.usuario (pn_id);

-- ---------------------------------------------------------------- TICKETS

CREATE TABLE IF NOT EXISTS public.ticket (
    pn_id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_titulo               varchar(255) NOT NULL,
    s_descripcion          text NOT NULL,
    s_sede                 varchar(255),
    s_solicitante_nombre   varchar(100),
    s_prioridad            varchar(20) DEFAULT 'NORMAL' NOT NULL,
    s_justificacion        text,
    plan_trabajo_clave     integer,
    d_fecha_fin            timestamp(6),
    fn_estadoticket_id     bigint NOT NULL REFERENCES public.estadoticket (pn_id),
    fn_usuario_area_id     bigint NOT NULL REFERENCES public.usuario (pn_id),
    fn_usuario_soporte_id  bigint REFERENCES public.usuario (pn_id),
    s_creado_por           varchar(100),
    d_fecha_creacion       timestamp(6) NOT NULL,
    s_modificado_por       varchar(100),
    d_fecha_modificacion   timestamp(6)
);

CREATE TABLE IF NOT EXISTS public.bitacora (
    pn_id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_estatus_registrado   varchar(50) NOT NULL,
    s_justificacion        text,
    fn_ticket_id           bigint NOT NULL REFERENCES public.ticket (pn_id),
    s_creado_por           varchar(100),
    d_fecha_creacion       timestamp(6) NOT NULL,
    s_modificado_por       varchar(100),
    d_fecha_modificacion   timestamp(6)
);

CREATE TABLE IF NOT EXISTS public.aviso (
    pn_id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_titulo              varchar(150) NOT NULL,
    s_mensaje             text NOT NULL,
    b_activo              boolean NOT NULL,
    b_eliminado           boolean DEFAULT false NOT NULL,
    -- Sin area = aviso global para toda la institucion.
    pn_area_id            bigint,
    s_creado_por          varchar(100),
    d_fecha_creacion      timestamp(6) NOT NULL,
    s_modificado_por      varchar(100),
    d_fecha_modificacion  timestamp(6)
);

-- ------------------------------------------------- MODULOS OPERATIVOS DE TI

-- Catalogo de equipos, para no repetir marca y modelo en cada dictamen.
CREATE TABLE IF NOT EXISTS public.equipo (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion     varchar(255) NOT NULL UNIQUE,
    marca           varchar(255),
    modelo          varchar(255),
    fecha_registro  timestamp(6)
);

-- Prestamos temporales de equipo al personal.
CREATE TABLE IF NOT EXISTS public.resguardo (
    pn_id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_equipo_nombre        varchar(100) NOT NULL,
    s_numero_serie         varchar(50) NOT NULL,
    s_numero_inventario    varchar(50),
    s_accesorios           text,
    s_condiciones          text,
    s_solicitante_nombre   varchar(100) NOT NULL,
    s_solicitante_numero   varchar(30) NOT NULL,
    s_departamento         varchar(100),
    s_telefono             varchar(50),
    s_estado_resguardo     varchar(20) NOT NULL,
    d_fecha_vencimiento    timestamp(6),
    fn_usuario_creador_id  bigint NOT NULL REFERENCES public.usuario (pn_id),
    -- Columnas heredadas de una version anterior, duplicadas de las s_*.
    -- Se conservan por compatibilidad; ver V3 para su retirada.
    condiciones            varchar(255),
    departamento           varchar(255),
    numero_inventario      varchar(255),
    telefono               varchar(255),
    s_creado_por           varchar(100),
    d_fecha_creacion       timestamp(6) NOT NULL,
    s_modificado_por       varchar(100),
    d_fecha_modificacion   timestamp(6),
    CONSTRAINT resguardo_s_estado_resguardo_check
        CHECK (s_estado_resguardo IN ('ENTREGADO', 'DEVUELTO', 'VENCIDO'))
);

-- Equipos recibidos en el taller para reparacion.
CREATE TABLE IF NOT EXISTS public.equipo_reparacion (
    pn_id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_folio                varchar(50) NOT NULL UNIQUE,
    s_equipo_tipo          varchar(100) NOT NULL,
    s_marca                varchar(100),
    s_modelo               varchar(100),
    s_numero_serie         varchar(100),
    s_numero_inventario    varchar(100),
    s_accesorios           varchar(500),
    s_condicion_recepcion  varchar(500),
    s_falla_reportada      varchar(1000),
    s_diagnostico          varchar(1000),
    s_solucion             varchar(1000),
    s_estado_taller        varchar(50) NOT NULL,
    s_solicitante_nombre   varchar(200) NOT NULL,
    s_solicitante_numero   varchar(50),
    s_departamento         varchar(150),
    fn_ticket_id           bigint,
    fn_tecnico_id          bigint REFERENCES public.usuario (pn_id),
    s_creado_por           varchar(100),
    d_fecha_creacion       timestamp(6) NOT NULL,
    s_modificado_por       varchar(100),
    d_fecha_modificacion   timestamp(6)
);

-- Control de altas y bajas de correo institucional.
CREATE TABLE IF NOT EXISTS public.correo_institucional (
    pn_id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_nombre                varchar(100) NOT NULL,
    s_apellido_paterno      varchar(100) NOT NULL,
    s_apellido_materno      varchar(100),
    s_correo                varchar(150) NOT NULL UNIQUE,
    s_area                  varchar(150) NOT NULL,
    s_cargo                 varchar(150),
    s_extension             varchar(20),
    s_cuota_almacenamiento  varchar(30),
    s_estado                varchar(50) NOT NULL,
    s_creado_por            varchar(100),
    d_fecha_creacion        timestamp(6) NOT NULL,
    s_modificado_por        varchar(100),
    d_fecha_modificacion    timestamp(6)
);

-- Actividades del plan anual de trabajo del personal del area.
CREATE TABLE IF NOT EXISTS public.actividad_extra (
    pn_id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_actividad_solicitada   varchar(255) NOT NULL,
    d_fecha_actividad        timestamp(6) NOT NULL,
    s_justificacion          text,
    s_situacion_actual       varchar(50) NOT NULL,
    -- Clave de la meta del plan de trabajo a la que se imputa.
    plan_trabajo_clave       integer NOT NULL,
    fn_usuario_id            bigint NOT NULL REFERENCES public.usuario (pn_id),
    s_creado_por             varchar(100),
    d_fecha_creacion         timestamp(6) NOT NULL,
    s_modificado_por         varchar(100),
    d_fecha_modificacion     timestamp(6)
);
