# Configuración de Conexión a la Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_tickets_db
spring.datasource.username=postgres
spring.datasource.password=pass123
spring.datasource.driver-class-name=org.postgresql.Driver

# Propiedades de JPA / Hibernate
# 'update' creará y modificará las tablas de la BD de forma automática según las entidades java.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Muestra en consola de desarrollo las consultas SQL ejecutadas
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- CONFIGURACIÓN DEL BOT DE TELEGRAM ---
telegram.bot.username=Emmanuel_pruebas_dev_bot
telegram.bot.token=8676341174:AAH1GDHaST6Ze0Tkby_8hCicz6Bimg7h86o